default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: teste_netshowme_development

test:
  <<: *default
  database: teste_netshowme_test

production:
  <<: *default
  database: teste_netshowme_production
  username: teste_netshowme
  password: <%= ENV['TESTE_NETSHOWME_DATABASE_PASSWORD'] %>
